name: Basic Pipeline

on:
  pull_request:
    branches: 
      - "main"

jobs:
  pr_metrics:
    name: Etiquetado
    runs-on: ubuntu-latest
    permissions:
        pull-requests: write
        statuses: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: microsoft/PR-Metrics@v1.6.5
        env:
          PR_METRICS_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  conventional-commits:
    if: ${{ github.event_name == 'pull_request' }}
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Install gitlint
        shell: bash
        run: |
          python -m pip install gitlint
      - name: Run gitlint
        shell: bash
        run: |
          # Lint everything from the base to the latest
          gitlint --commits "${{ github.event.pull_request.base.sha }}..HEAD" \
            -c general.contrib=contrib-title-conventional-commits \
            -c general.ignore=body-is-missing,body-max-line-length \
            -c title-max-length.line-length=100

  compilacion:
    name: Compilacion del proyecto
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    #- uses: actions/setup-dotnet@v4
     # with:
     #   dotnet-version: 6.x
     #   cache: true
    #- run: dotnet restore --locked-mode
    - run: dotnet build "Unidad 5 Hilos/EjemploHilos.sln" -c Release
    #- run: dotnet test --no-build --configuration Release 

    - name: List files in the repository
      run: |
        echo "Listando los archivos en el repositorio:"
        ls -R # Esto lista todos los archivos recursivamente
        echo "-------------------------------------"
        echo "Archivos en la carpeta src:"
        ls "Unidad 5 Hilos"  # O cualquier otra carpeta que desees listar
        echo "-------------------------------------"

    - uses: actions/upload-artifact@v4
      with:
        name: release-test.zip
        path: |
            "./Unidad 5 Hilos/EjemploMutex/**/Release/*.*" # or path/to/artifact
            "./Unidad 5 Hilos/EjemploMonitor/**/Release/*.*" # or path/to/artifact
            "./Unidad 5 Hilos/EjemploJoin/**/Release/*.*" # or path/to/artifact
            "D:\a\DiplomaturaNet\DiplomaturaNet\Unidad 5 Hilos\EjemploHilos\bin\Release\**" # or path/to/artifact

    continue-on-error: true
