name: Basic Pipeline

on:
  pull_request:
    branches: 
      - "main"

jobs:
  pr_metrics:
    name: Etiquetado
    runs-on: ubuntu-latest
    permissions:
        pull-requests: write
        statuses: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: microsoft/PR-Metrics@v1.6.5
        env:
          PR_METRICS_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  compilacion:
    name: Compilacion del proyecto
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    #- uses: actions/setup-dotnet@v4
     # with:
     #   dotnet-version: 6.x
     #   cache: true
    #- run: dotnet restore --locked-mode
    - run: dotnet build "Unidad 5 Hilos/EjemploHilos.sln" -c Release

    - uses: actions/upload-artifact@v4
      with:
        name: release-test.zip
        path: |
            "Unidad 5 Hilos/EjemploMutex/bin/Release" # or path/to/artifact
            "Unidad 5 Hilos/EjemploMonitor/bin/Release" # or path/to/artifact
            "Unidad 5 Hilos/EjemploJoin/bin/Release" # or path/to/artifact
            "Unidad 5 Hilos/EjemploInterlocked/bin/Release" # or path/to/artifact
            "Unidad 5 Hilos/AsyncAwait/bin/Release" # or path/to/artifact

    continue-on-error: true
